baseURL = 'https://blogcrcode.netlify.app/' 
languageCode = 'pt-br'
title = 'CRCode Blog'
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "OlÃ¡, sou o Carlos Roberto ðŸ‘‹"
    Content = """
    Bem-vindo ao meu blog pessoal.
    Aqui compartilho meus estudos sobre **Linux**, **Backend (Go/Python/C#)** e **CiberseguranÃ§a**.
    """


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/carlosr-sh"
  
  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@CRCode"

# Menu do Topo
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

[permalinks]
  posts = '/:year/:month/:day/:slug/'