backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Onde o CMS salva as imagens upadas
public_folder: "/images"      # Como a imagem aparece no Markdown

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Rascunho", name: "draft", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Autor", name: "author", widget: "string", default: "Carlos"}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}